### ISSUE TITLE
Add download websites in 2_packages.md

### ISSUE THREAD

**Issue by terryasdf** [Unturned3/Microdot#16]
It will be much more convenient to get those packages using `wget` command if available websites are given in 2_packages.md.

Here are all the websites:
- https://ftp.gnu.org/gnu/binutils/binutils-2.30.tar.gz
- https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.18.5.tar.gz
- https://ftp.gnu.org/gnu/mpfr/mpfr-4.0.1.tar.xz
- https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
- https://ftp.gnu.org/pub/gnu/gmp/gmp-6.1.2.tar.xz
- https://ftp.gnu.org/gnu/gcc/gcc-7.3.0//gcc-7.3.0.tar.gz
- http://git.musl-libc.org/cgit/musl/snapshot/musl-1.1.20.tar.gz
- https://busybox.net/downloads/busybox-1.30.0.tar.bz2

**Comment by Unturned3** [comment]
updated.
