### ISSUE TITLE
[Factual Error] Change "mudflap" to "libmudflap"

### ISSUE THREAD

**Issue by Unturned3** [Unturned3/Microdot#17]
In section "libgcc" at page https://github.com/Unturned3/Microdot/blob/master/wiki/3_miniSystem/2_install.md#libgcc

change --disable-mudflap to --disable-libmudflap

**Comment by concatime** [comment]
Hi. My comment has nothing to do with this repo., but I’ve found no other way to contact you. Did you solve this issue: https://www.linuxquestions.org/questions/linux-software-2/how-to-install-a-native-gcc-toolchain-onto-the-target-platform-4175643535/
```
ctype_members.cc: In constructor 'std::ctype_byname<char>::ctype_byname(const char*, std::size_t)':
ctype_members.cc:50:44: error: cannot convert 'const short unsigned int*' to 'const m
ask*' {aka 'const unsigned int*'} in assignment
   50 |  this->_M_table = this->_M_c_locale_ctype->__ctype_b;
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
      |                                            |
      |                                            const short unsigned int*
make[5]: *** [Makefile:642: ctype_members.lo] Error 1
```
I’m trying to build LFS but replacing glibc with musl (unlike you, I’ve build libstdc++).

EDIT: nvm, solved it.

**Comment by Unturned3** [comment]
Hello concatime,
Apologies for the *very* late response. I thought that github would send email notifications if someone wrote a comment, but I am wrong. Unfortunately I didn't manage to solve it, and gave up a while later. Instead, I just used another build method (adapted from musl-cross-make from richfelker).

**Comment by Unturned3** [comment]
Fixed.
