### ISSUE TITLE
dead links in document 1_prereq.md

### ISSUE THREAD

**Issue by billbill8** [Unturned3/Microdot#2]
url: https://github.com/Unturned3/Microdot/blob/master/wiki/1_intro/1_prereq.md

quotes:
linuxcommand.org
ryanstutorial.net/linuxtutorial
linux-tutorial.info

 open up a new Issue on GitHub

**Comment by Unturned3** [comment]
Hello billbill8, these links will be fixed soon.

**Comment by Unturned3** [comment]
fixed
