### ISSUE TITLE
failed to build static libgcc  in 3_bbuild.md

### ISSUE THREAD

**Issue by plusangel** [Unturned3/Microdot#27]
**Describe the bug**
Trying to build the static libgcc, I executed the following command:

`make -jN MAKE="make enable_shared=no" all-target-libgcc`

and it failed, giving me:

```
configure:5954: gcc -o conftest -g -O2  -I$$r/$(HOST_SUBDIR)/gmp -I$$s/gmp -I$$r/$(HOST_SUBDIR)/mpfr/src -I$$s/mpfr/src -I$$s/mpc/src     -lisl -L$$r/$(HOST_SUBDIR)/gmp/.libs -L$$r/$(HOST_SUBDIR)/mpfr/src/.libs -L$$r/$(HOST_SUBDIR)/mpc/src/.libs -lmpc -lmpfr -lgmp conftest.c  -lisl -lgmp >&5
conftest.c:10:10: fatal error: isl/schedule.h: No such file or directory
 #include <isl/schedule.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.

```
I think that I haven't missed a step. Could you think of any solution?

I don't if In need to try the `--no-isl` configuration option?

**Comment by Unturned3** [comment]
Hello,
I'll re-test my procedures and see if I can reproduce the issue.
Meanwhile, can you give me some info on your environment? (e.g. Linux distro/version, etc.)
Are you using the specified package versions or did you use some other version?
This will make it easier for us to pinpoint or reproduce the problem.

**Comment by Unturned3** [comment]
Hmm... I just checked my system's packages (installed by default along the base Debian system) and ISL seems to be one of them. Perhaps the current compilation process doesn't isolate the build from the host system too well, so bits of the pre-installed libraries on the host system can leak in.
I'll verify this soon. Maybe the --with-native-system-headers-dir=... flag is needed during GCC compilation.

**Comment by plusangel** [comment]
Hello, thank you very much for your attention and your quick reply. Yes, my system is an Ubuntu 18 desktop version.

Regarding the packages, I downloaded the links suggestions.

**Comment by Unturned3** [comment]
Seems like I may need to add the ISL package requirement... Can you check if ISL is installed on your Ubuntu 18 system?

**Comment by plusangel** [comment]
No. it is not installed

**Comment by Unturned3** [comment]
Ok I've finally verified this... ISL is indeed a dependency. I may have already installed it in the VM I tested the build with, so I did not notice.
