### ISSUE TITLE
make install-gcc

### ISSUE THREAD

**Issue by imlinus** [Unturned3/Microdot#28]
**Describe the bug**
What the bug is, what should the expected behavior be, etc.

I can't get past make install-gcc right now. I think it's something with the configuration, but I'm not quite certain.

Do you perhaps have any ideas?

Cheers! And thank you for creating such a wonderful tutorial

**Steps to reproduce the behavior** (if applicable)

**Additional context** (if applicable)
```bash
builder@VirtualBox:/opt/cross/src/gcc-7.3.0/build$ make install-gcc
/bin/bash ../mkinstalldirs /opt/cross /opt/cross
/bin/bash: line 3: cd: ./fixincludes: No such file or directory
make: *** [Makefile:3667: install-fixincludes] Error 1
```

**Comment by Unturned3** [comment]
Hey, sorry I just saw this issue

Just to confirm, is [this](https://github.com/Unturned3/Microdot/blob/master/wiki/2_crossToolchain/3_build.md#gcc-compile) the step that you are stuck on? Did you run `make all-gcc` before running `install-gcc`?

I didn't manage to find any similar errors on Google... very strange.

**Comment by Unturned3** [comment]
I just ran the step in my original build folder and the `fixincludes` folder did show up. Not too sure what's happening.
<img width="415" alt="Screenshot 2021-11-24 at 11 24 58" src="https://user-images.githubusercontent.com/36037753/143230902-4c2af3a1-552c-4441-a572-ad58f7393e6b.png">

**Comment by imlinus** [comment]
Hey mate! Let me run through the guide one more time and I'll get back to you. Thank you so much 👍

**Comment by imlinus** [comment]
I just tried it in a fresh docker container and it seems to work just fine so far! 👍
